### PR TITLE
Added the correct way to render the partial

### PR DESCRIPTION
**Pull request by jeremiahlukus**

### CODE REVIEW

**Comment by rsummro1** [comment]
I'm still not seeing the comments box.  Checking the code now to see if I have the modified version per the changes you communicated.  It shows above that I Merged your changes.

**Comment by jeremiahlukus** [comment]
Go to the terminal and type 'rails c'    then Comment.create( list_id: 1, forgot the other parameters)  then go to localhost:3000/comment

**Comment by rsummro1** [comment]
Oh, let me try that.  I was looking for the Comments box on the Show page...

**Comment by rsummro1** [comment]
Not sure what I'm supposed to do in the Rails Console?

**Comment by rsummro1** [comment]
Are you saying that I have to generate a Comment, in the Rails Console before I see the Comment box?

**Comment by rsummro1** [comment]
Got the following: No route matches [GET] "/comment"

**Comment by jeremiahlukus** [comment]
Well you cannot see any comments if there are none if you give me a few I'm about to get on my computer and I'll paste in how to create a new comment via console. Try /comments    not exactly sure which one it was ill respond in about 10 min and give you instructions on how to get it up on your machine.

**Comment by jeremiahlukus** [comment]
Did you pull the changes?
So you merged the pull request via github now you need to update your code. So go to your terminal and in the correct directory type git pull

**Comment by jeremiahlukus** [comment]
ok so go to your rails console

Type in `Link.create` this will give you 
`<Link id: nil, title: nil, url: nil, created_at: nil, updated_at: nil, user_id: nil>`

These are the params for creating a link 

So let's create a new link 
Assuing you have a user
`Link.create(title: "NEW Title", url: "google.com", user_id: User.last)` 

Now let's create a new comment for that link

`Comment.create(link_id: Link.last, body: "This is a comment", user_id: User.last)`

Now go to http://localhost:3000/comments

Your comments are now displayed

**Comment by rsummro1** [comment]
Okay, on the example I was following the box showed with a Comment count of
zero to enter a new comment.

How can Users enter new Comments?

Thanks for your time.



Royal



On Sat, Jan 20, 2018 at 11:17 AM, Jeremiah Parrack <notifications@github.com

**Comment by jeremiahlukus** [comment]
Well you have to make a form to enter a new comment that has a few hidden fields for user ID and link ID then the body. If I were you I would go back and re-read the tutorial. Since there are endless ways to implement this it might be better for you to just go back and follow the books way so it won't cause issues later on.

**Comment by jeremiahlukus** [comment]
From what I remember you did not program a way for users to enter new comments yet

**Pull request merged**
